const Base_url = "https://irhere.com.au/"/* "https://35.189.61.110/" */;

let link = "api/";

let image_base_url = "https://35.189.61.110/";

let android_map_key = "AIzaSyD4IakOtTxg5Ds4GhNEaHE03MQtFRE7tkE";
let ios_map_key = "AIzaSyBY2LBx91fNz4tvI4e1Gtu8ZGXJ0nTI43o";

let google_map_api_key = "&sensor=false&key=AIzaSyBosJOS3Vh5CqFhPW58AVdZ0AlZ_eWBE-I"

const constants =
{
    google_map_api_key: google_map_api_key,
    android_map_key: android_map_key,
    ios_map_key: ios_map_key,
    image_base_url: image_base_url,
    googleSignin: Base_url + link + "oauth/google/sign-in",
    registration: Base_url + link + "sign_up",
    signin: Base_url + link + "login",
    generate_Pattern: Base_url + link + "gravity_h",
    upload_video: Base_url + link + "upload_video",
    convert_video: Base_url + link + "process_video_thread_single",
    process_video: Base_url + link + "process_video_thread_two_single",
    set_user_mode: Base_url + link + "set_user_mode",
    check_mode_status: Base_url + link + "check_mode_status",
    update_user_mode: Base_url + link + "update_user_mode",
    add_questionnaire: Base_url + link + "add_questionnaire",
    get_certificate_list: Base_url + link + "get_certificate_list",
    verifyEmail: Base_url + link + "reset.php",
    total_miles: Base_url + link + "rides.php",
    total_rides: Base_url + link + "rides.php",
    total_badges: Base_url + link + "badges.php",
    total_deals: Base_url + link + "deals.php",
    weather_api: "https://api.openweathermap.org/data/2.5/weather",
    profile_pic_api: Base_url + link + "uploads.php",
    logout: Base_url + link + "logout",

    google_signin: Base_url + link + "oauth/google/sign-in",
    getPatientProfile: Base_url + link + "/media/profilepic",
    updatePatientProfile: Base_url + link + "media/upload?fileType=profilepic",
    patientInfo: Base_url + link + "patient/",
    patientExtraInfo: Base_url + link + "/patient/ext",
    surgicalprocedures: Base_url + link + "phr/surgicalprocedures",
    allergies: Base_url + link + "phr/allergies",
    conditions: Base_url + link + "phr/conditions",
    addFamilyMember: Base_url + link + "patient/caregiver",
    deleteFamilyMember: Base_url + link + "patient/caregivers/",
    FamilyCareTakerList: Base_url + link + "patient/ext",
    ProviderList: Base_url + link + "careprovider/list",
    AddProvider: Base_url + link + "careprovider/add",
    updatePatientInfo: Base_url + link + "patient/",
    updateExtraPatientInfo: Base_url + link + "/patient/ext",
    doctors: Base_url + link + "doctors",
    specialitySearch: Base_url + link + "doctors?specialty=",
    doctorDetails: Base_url + link + "doctor/",
    doctorTimeSlots: Base_url + link + "telemed/apt/",
    getSessionId: Base_url + link + "telemed/apt/",
    instantSession: Base_url + link + "telemed/session/instant",
    sendMessageToOnlineDoctor: Base_url + link + "message",
    appointmentCreate: Base_url + link + "/telemed/apt/create",
    getAllAppointment: Base_url + link + "/telemed/apt/self?fromDate=",
    cancelAppointment: Base_url + link + "telemed/apt/",
    submitFeedback: Base_url + link + "user/feedback",
    getFeedback: Base_url + link + "user/",
    labreports: Base_url + link + "media/labreports",
    healthinsurance: Base_url + link + "media/healthinsurance",
    uploadLabreports: Base_url + link + "media/upload?fileType=labreport",
    articles: Base_url + link + "articles/shared",
    detailArticle: Base_url + link + "articles",
    addVitals: Base_url + link + "vitals",
    latestVitals: Base_url + link + "vitals/latest",
    VitalDetail: Base_url + link + "vitals?vitalName=",
    notes: Base_url + link + "phr/notes",
    prescriptionList: Base_url + link + "telemed/sessions/",
    prescriptionDetail: Base_url + link + "telemed/session/",
    notification: Base_url + link + "notification/list",
    notificationDismiss: Base_url + link + "notification/dismiss",
    firebaseToken: Base_url + link + "device/gcm/registry",
    sendEmail: Base_url + link + "user/reset-password",
    sendcode: Base_url + link + "user/reset/",
    newPassword: Base_url + link + "user/reset",
    addMedication: Base_url + link + "phr/medication",
    getMedication: Base_url + link + "phr/medications",
    deleteMedication: Base_url + link + "phr/medications",
    getDevices: Base_url + link + "phr/devices",
    getInsurance: Base_url + link + "insurance",
    addDevice: Base_url + link + "/phr/device",
    addInsurance: Base_url + link + "insurance",
    message: Base_url + link + "message",
    getUrl: Base_url + link + "oauth/openepic/connect",
    blueButtonUrl: Base_url + link + "oauth/bluebutton/connect",
    AlexaUrl: Base_url + link + "oauth/alexa/connect",
    listOfProvider: Base_url + link + "openepic/me",
    listOfMedication: Base_url + link + "openepic/medications",
    listOfAppointment: Base_url + link + "openepic/appointments",
    listOfAllergies: Base_url + link + "openepic/allergies",
    listOfCondition: Base_url + link + "openepic/conditions" /* "openepic/vitals" */,
    listOfNotes: Base_url + link + "/openepic/notes",
    openePicDownload: Base_url + link + "openepic/download",
    Allergies: Base_url + link + "phr/allergies",
    Conditions: Base_url + link + "phr/conditions",
    Procedure: Base_url + link + "phr/surgicalprocedures",
    Immunizations: Base_url + link + "phr/immunizations",
    Notes: Base_url + link + "phr/notes",
    LabReport: Base_url + link + "labreports/patient/self",
    HealthInsuranceImage: Base_url + link + 'media/upload?fileType=healthinsurance',
    deleteDocument: Base_url + link + "media/delete/",
    AppointmentList: Base_url + link + "/appointments",
    Tracker: Base_url + link + "tracker",
    CancelInvite: Base_url + link + "/patient/caregivers/",
    DeleteAccount: Base_url + link + "user/terminate",
    AddNotes: Base_url + link + "phr/note",
    SwitchUser: Base_url + link + "caregiver/switch",
    SwitchBack: Base_url + link + "caregiver/logoff"
}

export default constants;